// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/sysctlpb/sysctl.proto

package sysctlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysctlService_GetMetrics_FullMethodName           = "/sysctl.SysctlService/GetMetrics"
	SysctlService_GetMetricsByCategory_FullMethodName = "/sysctl.SysctlService/GetMetricsByCategory"
	SysctlService_Subscribe_FullMethodName            = "/sysctl.SysctlService/Subscribe"
	SysctlService_ListKnownMetrics_FullMethodName     = "/sysctl.SysctlService/ListKnownMetrics"
	SysctlService_ListCategories_FullMethodName       = "/sysctl.SysctlService/ListCategories"
	SysctlService_GetKernelRegistry_FullMethodName    = "/sysctl.SysctlService/GetKernelRegistry"
)

// SysctlServiceClient is the client API for SysctlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SysctlService provides access to macOS kernel metrics via sysctl.
type SysctlServiceClient interface {
	// GetMetrics returns multiple sysctl metrics by name.
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	// GetMetricsByCategory returns all metrics in a category.
	GetMetricsByCategory(ctx context.Context, in *GetMetricsByCategoryRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	// Subscribe streams metric deltas at a client-requested interval.
	// Only metrics whose raw value changed since the last push are included.
	// The server rejects intervals faster than min_interval_ns from the registry.
	// Computed metrics are not supported — use GetMetrics for those.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error)
	// ListKnownMetrics returns all known/supported metric names.
	ListKnownMetrics(ctx context.Context, in *ListKnownMetricsRequest, opts ...grpc.CallOption) (*ListKnownMetricsResponse, error)
	// ListCategories returns all metric categories.
	ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
	// GetKernelRegistry returns the kernel metric registry for this platform.
	GetKernelRegistry(ctx context.Context, in *GetKernelRegistryRequest, opts ...grpc.CallOption) (*GetKernelRegistryResponse, error)
}

type sysctlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSysctlServiceClient(cc grpc.ClientConnInterface) SysctlServiceClient {
	return &sysctlServiceClient{cc}
}

func (c *sysctlServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, SysctlService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysctlServiceClient) GetMetricsByCategory(ctx context.Context, in *GetMetricsByCategoryRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, SysctlService_GetMetricsByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysctlServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SysctlService_ServiceDesc.Streams[0], SysctlService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SysctlService_SubscribeClient = grpc.ServerStreamingClient[SubscribeResponse]

func (c *sysctlServiceClient) ListKnownMetrics(ctx context.Context, in *ListKnownMetricsRequest, opts ...grpc.CallOption) (*ListKnownMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKnownMetricsResponse)
	err := c.cc.Invoke(ctx, SysctlService_ListKnownMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysctlServiceClient) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCategoriesResponse)
	err := c.cc.Invoke(ctx, SysctlService_ListCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysctlServiceClient) GetKernelRegistry(ctx context.Context, in *GetKernelRegistryRequest, opts ...grpc.CallOption) (*GetKernelRegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKernelRegistryResponse)
	err := c.cc.Invoke(ctx, SysctlService_GetKernelRegistry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysctlServiceServer is the server API for SysctlService service.
// All implementations must embed UnimplementedSysctlServiceServer
// for forward compatibility.
//
// SysctlService provides access to macOS kernel metrics via sysctl.
type SysctlServiceServer interface {
	// GetMetrics returns multiple sysctl metrics by name.
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	// GetMetricsByCategory returns all metrics in a category.
	GetMetricsByCategory(context.Context, *GetMetricsByCategoryRequest) (*GetMetricsResponse, error)
	// Subscribe streams metric deltas at a client-requested interval.
	// Only metrics whose raw value changed since the last push are included.
	// The server rejects intervals faster than min_interval_ns from the registry.
	// Computed metrics are not supported — use GetMetrics for those.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error
	// ListKnownMetrics returns all known/supported metric names.
	ListKnownMetrics(context.Context, *ListKnownMetricsRequest) (*ListKnownMetricsResponse, error)
	// ListCategories returns all metric categories.
	ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error)
	// GetKernelRegistry returns the kernel metric registry for this platform.
	GetKernelRegistry(context.Context, *GetKernelRegistryRequest) (*GetKernelRegistryResponse, error)
	mustEmbedUnimplementedSysctlServiceServer()
}

// UnimplementedSysctlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysctlServiceServer struct{}

func (UnimplementedSysctlServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedSysctlServiceServer) GetMetricsByCategory(context.Context, *GetMetricsByCategoryRequest) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetricsByCategory not implemented")
}
func (UnimplementedSysctlServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSysctlServiceServer) ListKnownMetrics(context.Context, *ListKnownMetricsRequest) (*ListKnownMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKnownMetrics not implemented")
}
func (UnimplementedSysctlServiceServer) ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCategories not implemented")
}
func (UnimplementedSysctlServiceServer) GetKernelRegistry(context.Context, *GetKernelRegistryRequest) (*GetKernelRegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKernelRegistry not implemented")
}
func (UnimplementedSysctlServiceServer) mustEmbedUnimplementedSysctlServiceServer() {}
func (UnimplementedSysctlServiceServer) testEmbeddedByValue()                       {}

// UnsafeSysctlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysctlServiceServer will
// result in compilation errors.
type UnsafeSysctlServiceServer interface {
	mustEmbedUnimplementedSysctlServiceServer()
}

func RegisterSysctlServiceServer(s grpc.ServiceRegistrar, srv SysctlServiceServer) {
	// If the following call panics, it indicates UnimplementedSysctlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysctlService_ServiceDesc, srv)
}

func _SysctlService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysctlServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysctlService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysctlServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysctlService_GetMetricsByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysctlServiceServer).GetMetricsByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysctlService_GetMetricsByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysctlServiceServer).GetMetricsByCategory(ctx, req.(*GetMetricsByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysctlService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SysctlServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SysctlService_SubscribeServer = grpc.ServerStreamingServer[SubscribeResponse]

func _SysctlService_ListKnownMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKnownMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysctlServiceServer).ListKnownMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysctlService_ListKnownMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysctlServiceServer).ListKnownMetrics(ctx, req.(*ListKnownMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysctlService_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysctlServiceServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysctlService_ListCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysctlServiceServer).ListCategories(ctx, req.(*ListCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysctlService_GetKernelRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKernelRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysctlServiceServer).GetKernelRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysctlService_GetKernelRegistry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysctlServiceServer).GetKernelRegistry(ctx, req.(*GetKernelRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SysctlService_ServiceDesc is the grpc.ServiceDesc for SysctlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysctlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sysctl.SysctlService",
	HandlerType: (*SysctlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetrics",
			Handler:    _SysctlService_GetMetrics_Handler,
		},
		{
			MethodName: "GetMetricsByCategory",
			Handler:    _SysctlService_GetMetricsByCategory_Handler,
		},
		{
			MethodName: "ListKnownMetrics",
			Handler:    _SysctlService_ListKnownMetrics_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _SysctlService_ListCategories_Handler,
		},
		{
			MethodName: "GetKernelRegistry",
			Handler:    _SysctlService_GetKernelRegistry_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _SysctlService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/sysctlpb/sysctl.proto",
}
