// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/sysctlpb/sysctl.proto

package sysctlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // e.g. "hw.memsize", "kern.hostname"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricRequest) Reset() {
	*x = GetMetricRequest{}
	mi := &file_proto_sysctlpb_sysctl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricRequest) ProtoMessage() {}

func (x *GetMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sysctlpb_sysctl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricRequest.ProtoReflect.Descriptor instead.
func (*GetMetricRequest) Descriptor() ([]byte, []int) {
	return file_proto_sysctlpb_sysctl_proto_rawDescGZIP(), []int{0}
}

func (x *GetMetricRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricResponse) Reset() {
	*x = GetMetricResponse{}
	mi := &file_proto_sysctlpb_sysctl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricResponse) ProtoMessage() {}

func (x *GetMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sysctlpb_sysctl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricResponse.ProtoReflect.Descriptor instead.
func (*GetMetricResponse) Descriptor() ([]byte, []int) {
	return file_proto_sysctlpb_sysctl_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetricResponse) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_proto_sysctlpb_sysctl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sysctlpb_sysctl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_sysctlpb_sysctl_proto_rawDescGZIP(), []int{2}
}

func (x *GetMetricsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_proto_sysctlpb_sysctl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sysctlpb_sysctl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_sysctlpb_sysctl_proto_rawDescGZIP(), []int{3}
}

func (x *GetMetricsResponse) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ListKnownMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnownMetricsRequest) Reset() {
	*x = ListKnownMetricsRequest{}
	mi := &file_proto_sysctlpb_sysctl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnownMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnownMetricsRequest) ProtoMessage() {}

func (x *ListKnownMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sysctlpb_sysctl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnownMetricsRequest.ProtoReflect.Descriptor instead.
func (*ListKnownMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_sysctlpb_sysctl_proto_rawDescGZIP(), []int{4}
}

type ListKnownMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*MetricInfo          `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnownMetricsResponse) Reset() {
	*x = ListKnownMetricsResponse{}
	mi := &file_proto_sysctlpb_sysctl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnownMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnownMetricsResponse) ProtoMessage() {}

func (x *ListKnownMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sysctlpb_sysctl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnownMetricsResponse.ProtoReflect.Descriptor instead.
func (*ListKnownMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_sysctlpb_sysctl_proto_rawDescGZIP(), []int{5}
}

func (x *ListKnownMetricsResponse) GetMetrics() []*MetricInfo {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Metric is a sysctl value with type information.
type Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Metric_StringValue
	//	*Metric_Uint64Value
	//	*Metric_Int64Value
	//	*Metric_Uint32Value
	//	*Metric_Int32Value
	//	*Metric_RawValue
	Value         isMetric_Value `protobuf_oneof:"value"`
	Error         string         `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"` // non-empty if the metric could not be read
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_sysctlpb_sysctl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sysctlpb_sysctl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_sysctlpb_sysctl_proto_rawDescGZIP(), []int{6}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() isMetric_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Metric) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Metric_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Metric) GetUint64Value() uint64 {
	if x != nil {
		if x, ok := x.Value.(*Metric_Uint64Value); ok {
			return x.Uint64Value
		}
	}
	return 0
}

func (x *Metric) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*Metric_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *Metric) GetUint32Value() uint32 {
	if x != nil {
		if x, ok := x.Value.(*Metric_Uint32Value); ok {
			return x.Uint32Value
		}
	}
	return 0
}

func (x *Metric) GetInt32Value() int32 {
	if x != nil {
		if x, ok := x.Value.(*Metric_Int32Value); ok {
			return x.Int32Value
		}
	}
	return 0
}

func (x *Metric) GetRawValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*Metric_RawValue); ok {
			return x.RawValue
		}
	}
	return nil
}

func (x *Metric) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type isMetric_Value interface {
	isMetric_Value()
}

type Metric_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Metric_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,3,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type Metric_Int64Value struct {
	Int64Value int64 `protobuf:"varint,4,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Metric_Uint32Value struct {
	Uint32Value uint32 `protobuf:"varint,5,opt,name=uint32_value,json=uint32Value,proto3,oneof"`
}

type Metric_Int32Value struct {
	Int32Value int32 `protobuf:"varint,6,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type Metric_RawValue struct {
	RawValue []byte `protobuf:"bytes,7,opt,name=raw_value,json=rawValue,proto3,oneof"`
}

func (*Metric_StringValue) isMetric_Value() {}

func (*Metric_Uint64Value) isMetric_Value() {}

func (*Metric_Int64Value) isMetric_Value() {}

func (*Metric_Uint32Value) isMetric_Value() {}

func (*Metric_Int32Value) isMetric_Value() {}

func (*Metric_RawValue) isMetric_Value() {}

// MetricInfo describes a known sysctl metric.
type MetricInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ValueType     string                 `protobuf:"bytes,3,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"` // "string", "uint64", "int32", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricInfo) Reset() {
	*x = MetricInfo{}
	mi := &file_proto_sysctlpb_sysctl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricInfo) ProtoMessage() {}

func (x *MetricInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sysctlpb_sysctl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricInfo.ProtoReflect.Descriptor instead.
func (*MetricInfo) Descriptor() ([]byte, []int) {
	return file_proto_sysctlpb_sysctl_proto_rawDescGZIP(), []int{7}
}

func (x *MetricInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetricInfo) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

var File_proto_sysctlpb_sysctl_proto protoreflect.FileDescriptor

const file_proto_sysctlpb_sysctl_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/sysctlpb/sysctl.proto\x12\x06sysctl\"&\n" +
	"\x10GetMetricRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\";\n" +
	"\x11GetMetricResponse\x12&\n" +
	"\x06metric\x18\x01 \x01(\v2\x0e.sysctl.MetricR\x06metric\")\n" +
	"\x11GetMetricsRequest\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\">\n" +
	"\x12GetMetricsResponse\x12(\n" +
	"\ametrics\x18\x01 \x03(\v2\x0e.sysctl.MetricR\ametrics\"\x19\n" +
	"\x17ListKnownMetricsRequest\"H\n" +
	"\x18ListKnownMetricsResponse\x12,\n" +
	"\ametrics\x18\x01 \x03(\v2\x12.sysctl.MetricInfoR\ametrics\"\x8f\x02\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12#\n" +
	"\fuint64_value\x18\x03 \x01(\x04H\x00R\vuint64Value\x12!\n" +
	"\vint64_value\x18\x04 \x01(\x03H\x00R\n" +
	"int64Value\x12#\n" +
	"\fuint32_value\x18\x05 \x01(\rH\x00R\vuint32Value\x12!\n" +
	"\vint32_value\x18\x06 \x01(\x05H\x00R\n" +
	"int32Value\x12\x1d\n" +
	"\traw_value\x18\a \x01(\fH\x00R\brawValue\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05errorB\a\n" +
	"\x05value\"a\n" +
	"\n" +
	"MetricInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"value_type\x18\x03 \x01(\tR\tvalueType2\xed\x01\n" +
	"\rSysctlService\x12@\n" +
	"\tGetMetric\x12\x18.sysctl.GetMetricRequest\x1a\x19.sysctl.GetMetricResponse\x12C\n" +
	"\n" +
	"GetMetrics\x12\x19.sysctl.GetMetricsRequest\x1a\x1a.sysctl.GetMetricsResponse\x12U\n" +
	"\x10ListKnownMetrics\x12\x1f.sysctl.ListKnownMetricsRequest\x1a .sysctl.ListKnownMetricsResponseB.Z,github.com/accretional/sysctl/proto/sysctlpbb\x06proto3"

var (
	file_proto_sysctlpb_sysctl_proto_rawDescOnce sync.Once
	file_proto_sysctlpb_sysctl_proto_rawDescData []byte
)

func file_proto_sysctlpb_sysctl_proto_rawDescGZIP() []byte {
	file_proto_sysctlpb_sysctl_proto_rawDescOnce.Do(func() {
		file_proto_sysctlpb_sysctl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sysctlpb_sysctl_proto_rawDesc), len(file_proto_sysctlpb_sysctl_proto_rawDesc)))
	})
	return file_proto_sysctlpb_sysctl_proto_rawDescData
}

var file_proto_sysctlpb_sysctl_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_sysctlpb_sysctl_proto_goTypes = []any{
	(*GetMetricRequest)(nil),         // 0: sysctl.GetMetricRequest
	(*GetMetricResponse)(nil),        // 1: sysctl.GetMetricResponse
	(*GetMetricsRequest)(nil),        // 2: sysctl.GetMetricsRequest
	(*GetMetricsResponse)(nil),       // 3: sysctl.GetMetricsResponse
	(*ListKnownMetricsRequest)(nil),  // 4: sysctl.ListKnownMetricsRequest
	(*ListKnownMetricsResponse)(nil), // 5: sysctl.ListKnownMetricsResponse
	(*Metric)(nil),                   // 6: sysctl.Metric
	(*MetricInfo)(nil),               // 7: sysctl.MetricInfo
}
var file_proto_sysctlpb_sysctl_proto_depIdxs = []int32{
	6, // 0: sysctl.GetMetricResponse.metric:type_name -> sysctl.Metric
	6, // 1: sysctl.GetMetricsResponse.metrics:type_name -> sysctl.Metric
	7, // 2: sysctl.ListKnownMetricsResponse.metrics:type_name -> sysctl.MetricInfo
	0, // 3: sysctl.SysctlService.GetMetric:input_type -> sysctl.GetMetricRequest
	2, // 4: sysctl.SysctlService.GetMetrics:input_type -> sysctl.GetMetricsRequest
	4, // 5: sysctl.SysctlService.ListKnownMetrics:input_type -> sysctl.ListKnownMetricsRequest
	1, // 6: sysctl.SysctlService.GetMetric:output_type -> sysctl.GetMetricResponse
	3, // 7: sysctl.SysctlService.GetMetrics:output_type -> sysctl.GetMetricsResponse
	5, // 8: sysctl.SysctlService.ListKnownMetrics:output_type -> sysctl.ListKnownMetricsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_sysctlpb_sysctl_proto_init() }
func file_proto_sysctlpb_sysctl_proto_init() {
	if File_proto_sysctlpb_sysctl_proto != nil {
		return
	}
	file_proto_sysctlpb_sysctl_proto_msgTypes[6].OneofWrappers = []any{
		(*Metric_StringValue)(nil),
		(*Metric_Uint64Value)(nil),
		(*Metric_Int64Value)(nil),
		(*Metric_Uint32Value)(nil),
		(*Metric_Int32Value)(nil),
		(*Metric_RawValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sysctlpb_sysctl_proto_rawDesc), len(file_proto_sysctlpb_sysctl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sysctlpb_sysctl_proto_goTypes,
		DependencyIndexes: file_proto_sysctlpb_sysctl_proto_depIdxs,
		MessageInfos:      file_proto_sysctlpb_sysctl_proto_msgTypes,
	}.Build()
	File_proto_sysctlpb_sysctl_proto = out.File
	file_proto_sysctlpb_sysctl_proto_goTypes = nil
	file_proto_sysctlpb_sysctl_proto_depIdxs = nil
}
